name: chatgpt
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  dartz: ^0.10.1
  dio: ^5.0.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  freezed_annotation: ^2.2.0
  go_router: ^6.2.0
  hooks_riverpod: ^2.3.1
  json_annotation: ^4.8.0
  retrofit: ^4.0.1

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  retrofit_generator: ^6.0.0+1

flutter:
  uses-material-design: true

  fonts:
    - family: DINNEXT
      fonts:
        - asset: assets/fonts/DINNEXT-Black.ttf
          weight: 900
        - asset: assets/fonts/DINNEXT-Bold.ttf
          weight: 700
        - asset: assets/fonts/DINNEXT-Medium.ttf
          weight: 500
        - asset: assets/fonts/DINNEXT-Regular.ttf
          weight: 400
        - asset: assets/fonts/DINNEXT-Light.ttf
          weight: 300
        - asset: assets/fonts/DINNEXT-UltraLight.ttf
          weight: 100
